version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - API_URL=https://deepl.tr1ck.cn/translate
      - SITE_DOMAIN=http://front
    ports:
      - 5001:5000
    restart: always

  front:
    build:
      context: ../front
      dockerfile: Dockerfile
    restart: always
